### ISSUE TITLE
Nixpkgs package

### ISSUE THREAD

**Issue by Rucadi** [Thomas-de-Bock/construct#10]
Hello!

I love this compiler and find it super interesting :)

I've open a PR on https://github.com/NixOS/nixpkgs/pull/289114 to get this utility available on nixpkgs.

This will allow other nixpkgs packages to depend on it to build their code, create my own flakes environment with this tool available and installing it easily with   nix/ home-manager/ nix-env / nix-shell.

**Comment by Thomas-de-Bock** [comment]
Wow that's amazing, thank you so much. Will the nix package be updated when I make changes here as well? Not sure how this works.

**Comment by Rucadi** [comment]
Not at all, 
The package must be updated manually, usually by contributors. 

If you are a maintainer of the package: 
![image](https://github.com/Thomas-de-Bock/construct/assets/6445619/a257b2eb-642b-4324-9898-36c032148ce9)
when someone wants to update or touch your package, you'll be automatically requested to review it and approve it.

Also, you can commit the changes related to the package.

I can add you as a coauthor and contributor probably, so you can review changes other people want to make.

It is usually good practice to just maintain the package up-to-date in nixpkgs, but if there is no major features we can also just skip it.

**Comment by Rucadi** [comment]
Issue https://github.com/Thomas-de-Bock/construct/issues/9

is blocking the inclusion on nixpkgs, could this be clarified somehow?

**Comment by Thomas-de-Bock** [comment]
Hey, I've added an MIT license.

**Comment by Rucadi** [comment]
It's my pleasure to announce that **construct**  has been merged into Nixpkgs!

To get a terminal with construct installed, if you have nix installed on any Linux x86/arm64 or macos you can perform:

$ nix shell nixpkgs/master#construct

(After that command it will be available on your PATH)

🎉🎉🎉
