### ISSUE TITLE
C++ standard

### ISSUE THREAD

**Issue by Rucadi** [Thomas-de-Bock/construct#11]
I would like to create some PR with improvements, however, I would like to use c++17 and c++20 features.

Have you decided in any maximum standard to support? 
Or I can go wild with newer c++ versions?

**Comment by Thomas-de-Bock** [comment]
I really would prefer if you kept it mostly to C++14 and below, unless there's somewhere where it would really be a big improvement. I wrote the code with the idea that I'd rewrite it in pure C at some point and I still want to follow that idea at least a little, I'm really not a fan of most newer C++ features.
