### ISSUE TITLE
Support for `macho` assembly output

### ISSUE THREAD

**Issue by BlueFalconHD** [Thomas-de-Bock/construct#12]
Adding support for outputting Mach-O assembly instead of Elf would be awesome (as of writing this, running on macOS produces errors when assembling & linking binaries produced by Construct)

**Comment by Thomas-de-Bock** [comment]
As I currently have no access to a mac machine I cannot provide MacOS support for construct.

**Comment by BlueFalconHD** [comment]
I do, let me know if any help is needed.
