### ISSUE TITLE
Better command formatting & argument

### ISSUE THREAD

**Issue by BlueFalconHD** [Thomas-de-Bock/construct#14]
Construct's command line arguments are awkward and hard to understand. To fix this, Construct could follow the likes of `nasm`, which is invoked like

```bash
nasm -f elf64 -o cool.o cool.asm
```

The input file doesn't use a flag, instead it is an unnamed argument. Also, flag names could have alternative long names, like `--format` for the `-f` flag, and so on.

**Comment by Thomas-de-Bock** [comment]
Ah that was actually the exact behaviour I was going for (besides the long name part) looks like I removed it somewhere along the line, I'll revert it along with some other changes.

**Comment by Thomas-de-Bock** [comment]
Thanks so much, fixed in latest commit and release.
