### ISSUE TITLE
Graceful error handling

### ISSUE THREAD

**Issue by BlueFalconHD** [Thomas-de-Bock/construct#15]
When running Construct with one of the examples (`factorial.con`), I get a malloc error. Construct should handle these gracefully and provide detailed error messages and fail gracefully.

```bash
blue@computer ~/D/c/examples [1]> construct -f elf64 -i factorial.con -o out.asm
construct(26020,0x1dd1d5ec0) malloc: *** error for object 0x600003bfc000: pointer being freed was not allocated
construct(26020,0x1dd1d5ec0) malloc: *** set a breakpoint in malloc_error_break to debug
fish: Job 1, 'construct -f elf64 -i factorial…' terminated by signal SIGABRT (Abort)
```

**Comment by Thomas-de-Bock** [comment]
Ah made a small typo in the factorial example file thanks for pointing it out, this shouldn't give an error actually. And yeah error logging is still very barebones.

**Comment by Thomas-de-Bock** [comment]
Thanks so much, fixed in latest commit and release.
