### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by boredcoder411** [Thomas-de-Bock/construct#17]
The project builds successfully, transpiling the factorial example exits without error, but when it comes to assembling the output, an error caused by the compiler occurs:
```
nasm -f elf64 factorial.asm -o factorial.o
factorial.asm:6: error: invalid combination of opcode and operands
factorial.asm:7: error: invalid combination of opcode and operands
factorial.asm:9: error: symbol `num' not defined
factorial.asm:19: error: invalid combination of opcode and operands
```
contents of factorial.asm produced by the compiler, not modified:
```as

global _start
extern printf
section .text
factorial:
mov rsi,
mov rax,
startwhile0:
cmp rsi, num
jg endwhile0
mul rsi
inc rsi
jmp startwhile0
endwhile0:
ret
_start:
call factorial
call printf
mov rax,
syscall
ret
section .data
fmt: db "%d", 10, 0
```

**Comment by Thomas-de-Bock** [comment]
Hey, thanks for letting me know. This bug was introduced when boost was removed as a dependency and a custom string_split function was added. Now fixed.
