### ISSUE TITLE
Another bug?

### ISSUE THREAD

**Issue by boredcoder411** [Thomas-de-Bock/construct#18]
Hi! Me again. I tried replicating the example from the video, like this:
```
dev@xmaspc:~/construct$ ./bin/construct -f elf64 -i examples/strlwr.con -o strlwr.asm
dev@xmaspc:~/construct$ nasm -f elf64 strlwr.asm -o strlwr.o
dev@xmaspc:~/construct$ ld strlwr.o -o strlwr -dynamic-linker $(which ld) -lc -m elf_x86_64
dev@xmaspc:~/construct$ ./strlwr
Segmentation fault
dev@xmaspc:~/construct$
```
As you can see, the commands are identical to the ones in the video.

**Comment by Thomas-de-Bock** [comment]
Hello, it appears you're using `$(which ld)` to specify the dynamic linker. The ld util and the ld-linux-x86-64.so.2 I used in the video are different things. Please try it again, specifying the x64 dynamic loader instead, thanks.
