### ISSUE TITLE
boost lib dependence

### ISSUE THREAD

**Issue by xbrgg** [Thomas-de-Bock/construct#8]
using boost 1.84 worked
-Iboost_1_84_0/

edit: boost is a library

file 'src/deconstruct.h'
#include<boost/algorithm/string/classification.hpp>
#include<boost/algorithm/string/split.hpp>
#include<boost/algorithm/string.hpp>

**Comment by NoneSince** [comment]
In PR #4 this will be fixed: @Thomas-de-Bock used two small functions so I implemented them and removed these headers

**Comment by Thomas-de-Bock** [comment]
Afaik the boost headers by default are installed to the default include directory ( + /boost) so no additional include should be required right? Also @NoneSince, your PR is still broken as of writing this, I suspect it has something do with with the boost::token_compress_on flag I originally passed specifically in parse_construct.

**Comment by NoneSince** [comment]
@Thomas-de-Bock, I don't have boost, and it is a non standard system (or should I say THE non-standard system).
I fixed split and now my PR generates the same .asm files as your master, so you can merge now
